"use client";

import AdminGuard from "@/components/AdminGuard";
import Link from "next/link";
import { ChangeEvent, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Database, Download, HeartPulse, RotateCcw, Trash2, Upload, XCircle } from "lucide-react";

type Diagnostic = { ok:boolean; checks:Record<string,{ok:boolean;detail:string}>; runtime:{node:string;timestamp:string} };

export default function SystemPage(){
 const [diagnostic,setDiagnostic]=useState<Diagnostic|null>(null); const [message,setMessage]=useState("");
 async function refresh(){const r=await fetch("/api/system/diagnostics");setDiagnostic(await r.json());}
 useEffect(()=>{void refresh();},[]);
 async function restore(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!confirm("Restore this backup into the current database? Existing IDs will be updated."))return;setMessage("Restoring...");const r=await fetch("/api/system/restore",{method:"POST",headers:{"content-type":"application/json"},body:await file.text()});const b=await r.json();setMessage(r.ok?`Restored ${b.restored.forms} forms and ${b.restored.responses} responses.`:b.error);}
 async function cleanup(){if(!confirm("Delete responses older than the configured retention period? This cannot be undone."))return;setMessage("Cleaning...");const r=await fetch("/api/system/cleanup",{method:"POST"});const b=await r.json();setMessage(r.ok?`Deleted ${b.deleted} old responses.`:b.error);}
 return <AdminGuard><main className="min-h-screen bg-slate-50 px-5 py-8"><div className="mx-auto max-w-5xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft size={16}/>Dashboard</Link><div className="mt-5"><p className="text-sm font-semibold text-violet-600">Operations</p><h1 className="text-3xl font-bold">Health, backup, and recovery</h1><p className="mt-2 text-slate-500">Check deployment readiness and manage recoverable copies of forms and responses.</p></div>{message&&<div className="mt-5 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
 <div className="mt-7 grid gap-5 lg:grid-cols-2"><section className="card p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><HeartPulse className="text-violet-600"/><h2 className="text-xl font-bold">Diagnostics</h2></div><button className="btn-secondary" onClick={refresh}><RotateCcw size={16} className="mr-2"/>Run checks</button></div><div className="mt-5 space-y-3">{diagnostic?Object.entries(diagnostic.checks).map(([name,check])=><div key={name} className="flex items-start gap-3 rounded-xl border border-slate-200 p-4">{check.ok?<CheckCircle2 className="text-emerald-600"/>:<XCircle className="text-rose-600"/>}<div><p className="font-semibold capitalize">{name}</p><p className="text-sm text-slate-500">{check.detail}</p></div></div>):<p className="text-sm text-slate-500">Running checks...</p>}</div></section>
 <section className="card p-6"><div className="flex items-center gap-3"><Database className="text-violet-600"/><h2 className="text-xl font-bold">Backup and restore</h2></div><p className="mt-2 text-sm text-slate-500">Backups include forms, responses, and system settings in a portable JSON file.</p><div className="mt-5 grid gap-3"><a href="/api/system/backup" className="btn-primary justify-center"><Download size={17} className="mr-2"/>Download full backup</a><label className="btn-secondary cursor-pointer justify-center"><Upload size={17} className="mr-2"/>Restore backup<input type="file" accept="application/json,.json" className="hidden" onChange={restore}/></label><button className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 font-semibold text-rose-700" onClick={cleanup}><Trash2 size={17} className="mr-2 inline"/>Run retention cleanup</button></div></section></div>
 <section className="card mt-5 p-6"><h2 className="text-xl font-bold">Recovery checklist</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><Tip title="Before deployments" text="Download a backup before schema or application upgrades."/><Tip title="After deployments" text="Run diagnostics and submit one test response."/><Tip title="Before cleanup" text="Keep an offline backup before permanently deleting old responses."/></div></section>
 </div></main></AdminGuard>}
function Tip({title,text}:{title:string;text:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-slate-500">{text}</p></div>}
