"use client";
import AdminGuard from "@/components/AdminGuard";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, CopyPlus, FileText, Library, Search, Trash2 } from "lucide-react";
import { createFormFromTemplate, deleteQuestionBankItem, deleteTemplate, listQuestionBank, listTemplates, setTemplateArchived, type FormTemplate, type QuestionBankItem } from "@/lib/template-store";

export default function TemplatesPage() {
  const router = useRouter();
  const [templates, setTemplates] = useState<FormTemplate[]>([]);
  const [bank, setBank] = useState<QuestionBankItem[]>([]);
  const [query, setQuery] = useState("");
  const [tab, setTab] = useState<"templates" | "questions">("templates");
  function refresh() { setTemplates(listTemplates()); setBank(listQuestionBank()); }
  useEffect(refresh, []);
  const visibleTemplates = useMemo(() => templates.filter((item) => `${item.name} ${item.category} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [templates, query]);
  const visibleBank = useMemo(() => bank.filter((item) => `${item.name} ${item.category} ${item.question.title}`.toLowerCase().includes(query.toLowerCase())), [bank, query]);
  async function useTemplate(template: FormTemplate) { const form = await createFormFromTemplate(template); router.push(`/forms/${form.id}/edit`); }
  return <AdminGuard><main className="min-h-screen bg-[#f7f8fc] p-5 sm:p-8"><div className="mx-auto max-w-6xl">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/dashboard" className="text-sm font-semibold text-violet-700">← Dashboard</Link><h1 className="mt-2 text-3xl font-bold">Templates & question bank</h1><p className="mt-2 text-slate-500">Reuse complete forms or individual questions without rebuilding them.</p></div><Link href="/forms/new" className="btn-primary">Create blank form</Link></div>
    <div className="mt-7 flex flex-wrap items-center gap-3"><button className={tab === "templates" ? "btn-primary" : "btn-secondary"} onClick={() => setTab("templates")}><FileText size={16} className="mr-2"/>Templates</button><button className={tab === "questions" ? "btn-primary" : "btn-secondary"} onClick={() => setTab("questions")}><Library size={16} className="mr-2"/>Question bank</button><div className="relative ml-auto min-w-64"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="field pl-10" placeholder="Search reusable content" value={query} onChange={(e) => setQuery(e.target.value)}/></div></div>
    {tab === "templates" ? <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visibleTemplates.map((template) => <article key={template.id} className={`card p-5 ${template.archived ? "opacity-60" : ""}`}><div className="flex items-start justify-between"><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">{template.category}</span><span className="text-xs text-slate-400">{template.form.questions.length} questions</span></div><h2 className="mt-4 text-xl font-bold">{template.name}</h2><p className="mt-2 line-clamp-2 text-sm text-slate-500">{template.description || "Reusable internal form template"}</p><div className="mt-5 flex flex-wrap gap-2"><button className="btn-primary flex-1" disabled={template.archived} onClick={() => void useTemplate(template)}><CopyPlus size={16} className="mr-2"/>Use template</button><button className="builder-icon-button" title={template.archived ? "Restore" : "Archive"} onClick={() => { setTemplateArchived(template.id, !template.archived); refresh(); }}><Archive size={17}/></button><button className="builder-icon-button text-rose-500" onClick={() => { if (confirm("Delete this template?")) { deleteTemplate(template.id); refresh(); } }}><Trash2 size={17}/></button></div></article>)}{!visibleTemplates.length && <div className="card p-10 text-center md:col-span-2 xl:col-span-3"><FileText className="mx-auto text-slate-300" size={42}/><h2 className="mt-4 text-xl font-bold">No templates yet</h2><p className="mt-2 text-slate-500">Open any form and choose “Save as template”.</p></div>}</div> : <div className="mt-6 grid gap-4 md:grid-cols-2">{visibleBank.map((item) => <article key={item.id} className="card p-5"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{item.category}</span><h2 className="mt-3 text-lg font-bold">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.question.type.replaceAll("_", " ")} · {item.question.required ? "Required" : "Optional"}{item.question.scoreEnabled ? ` · ${item.question.points || 0} points` : ""}</p></div><button className="builder-icon-button text-rose-500" onClick={() => { deleteQuestionBankItem(item.id); refresh(); }}><Trash2 size={17}/></button></div></article>)}{!visibleBank.length && <div className="card p-10 text-center md:col-span-2"><Library className="mx-auto text-slate-300" size={42}/><h2 className="mt-4 text-xl font-bold">Question bank is empty</h2><p className="mt-2 text-slate-500">Save reusable questions from inside the form builder.</p></div>}</div>}
  </div></main></AdminGuard>;
}
